apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: codering-ui
  namespace: codering
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: localhost:5000/codering-ui:latest
        ports:
        - containerPort: 80
