apiVersion: v1
kind: Service
metadata:
  name: codering-ui
  namespace: codering
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: master
  type: LoadBalancer
