version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      # pour tester le build de prod en local, passer par Kubernetes (minikube)
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./src:/var/www/src
      - /var/www/node_modules
